spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/project-be-demo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driverClass: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  main:
#    allow-bean-definition-overriding: true
#  spring.jpa.hibernate.ddl-auto=update
#  spring.jpa.show-sql=true

server:
  port: 8380




logging:
  level:
    com.xkcoding: debug
    com.xkcoding.orm.mybatis.mapper: trace
mybatis:
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.dbin.entity
